local util = require("jira.common.util")

describe("util", function()
  describe("format_time", function()
    it("should return 0 for nil or <= 0", function()
      assert.are.equal("0", util.format_time(nil))
      assert.are.equal("0", util.format_time(0))
      assert.are.equal("0", util.format_time(-10))
    end)

    it("should format seconds to hours", function()
      assert.are.equal("1", util.format_time(3600))
      assert.are.equal("2", util.format_time(7200))
    end)

    it("should show one decimal place for non-integers", function()
      assert.are.equal("0.5", util.format_time(1800))
      assert.are.equal("1.5", util.format_time(5400))
    end)
  end)

  describe("strim", function()
    it("should remove leading and trailing whitespace", function()
      assert.are.equal("hello", util.strim("  hello  "))
      assert.are.equal("hello world", util.strim("\n hello world \t"))
    end)
  end)

  describe("markdown_to_adf", function()
    it("should convert simple text to ADF", function()
      local adf = util.markdown_to_adf("hello world")
      assert.are.equal("doc", adf.type)
      assert.are.equal(1, #adf.content)
      assert.are.equal("paragraph", adf.content[1].type)
      assert.are.equal("hello world", adf.content[1].content[1].text)
    end)

    it("should handle bold text", function()
      local adf = util.markdown_to_adf("hello **world**")
      local content = adf.content[1].content
      assert.are.equal("hello ", content[1].text)
      assert.are.equal("world", content[2].text)
      assert.are.equal("strong", content[2].marks[1].type)
    end)

    it("should handle links", function()
      local adf = util.markdown_to_adf("[Google](https://google.com)")
      local content = adf.content[1].content
      assert.are.equal("Google", content[1].text)
      assert.are.equal("link", content[1].marks[1].type)
      assert.are.equal("https://google.com", content[1].marks[1].attrs.href)
    end)

    it("should handle multiple paragraphs", function()
      local adf = util.markdown_to_adf("p1\n\np2")
      assert.are.equal(2, #adf.content)
      assert.are.equal("p1", adf.content[1].content[1].text)
      assert.are.equal("p2", adf.content[2].content[1].text)
    end)
  end)
end
